name: hello-world 
# attribute provides useful organizational information when returning warnings, errors, and output
on: push
# The on is the name of the GitHub event that triggers the workflow
jobs:
# jobs level contains a collection of jobs that make up the workflow.
  my-job:
  # my-job is an example of the name for a job
    runs-on: ubuntu-latest
    # runs-on describes on which operating system the pipeline should run
    steps:
    # steps collection is an ordered list of run directives
      - name: my-step
        run: echo "Hello World!"
        #ach run directive is executed in the order in which it is declared
      - name: second-step
        run: echo "Hallo again!"